---

- name: Create the network configuration file for ethernet devices
  template: src=ethernet_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: "{{ network_ether_interfaces }}"
  when: network_ether_interfaces is defined
  notify: restart network
  tags:
  - arp
  - network
  - dns
  - rclocal

- name: Register network_ether_interfaces_configured
  set_fact:
    network_ether_interfaces_configured: "[{% for item in network_ether_interfaces | default([]) -%}\n  u\"{{ net_path }}/ifcfg-{{ item.device }}\"\n  {{ '' if loop.last else ',' }}\n{%- endfor %}]\n"
  changed_when: false
  tags:
  - arp
  - network
  - dns
  - rclocal

- name: Write configuration files for rhel route configuration
  template: src=route_{{ ansible_os_family }}.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: "{{ network_ether_interfaces }}"
  when:
  - network_ether_interfaces is defined
  - item.route is defined
  notify: restart network
  tags:
  - arp
  - network
  - dns
  - rclocal

- name: Register network_ether_interfaces_routes_configured
  set_fact:
    network_ether_interfaces_routes_configured: "[{% for item in network_ether_interfaces | default([]) -%}\n {% if item.route is defined %}\n  u\"{{ net_path }}/route-{{ item.device }}\"\n  {{ ',' }}\n {% endif %}\n {% if loop.last %}\n  {{ '' }}\n {% endif %}\n{%- endfor %}]\n"
  changed_when: false
  tags:
  - arp
  - network
  - dns
  - rclocal

