---

- name: Ensure rsyslog is started and enabled on boot
  service:
    name: rsyslog
    state: started
    enabled: yes
  tags:
  - rsyslog
  - common

# https://access.redhat.com/solutions/1564823
- name: Remove session messages from logs
  template:
    src: rsyslog_ignore_systemd_session_slice.conf.j2
    dest: /etc/rsyslog.d/ignore-systemd-session-slice.conf
  notify: restart rsyslog
  tags:
  - rsyslog
  - common
